medishop/medishopproject/medishopapp/urls.py
from django.urls import path

from . import views

app_name='medishop'

urlpatterns = [
    path('',views.index,name='index'),
    path('product/<int:product_id>',views.detail,name='detail'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('alomeds',views.alloitems,name='alloitems'),
    path('homeomeds',views.homeitems,name='homeitems'),
    path('ayurmeds',views.ayuritems,name='ayuritems'),
    path('thank', views.thank, name='thank'),

]

medishop/medishopproject/medishopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('medishopapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medishop/medishopproject/medishopapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name=models.CharField(max_length=255,unique=True)
    description=models.TextField(blank=True)
    img=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name=models.CharField(max_length=255,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    img=models.ImageField(upload_to='product',blank=True)




    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

medishop/medishopproject/medishopapp/views.py
from django.http import HttpResponse
from . models import Category,Product
from django.shortcuts import render
from django.contrib import auth, messages
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.models import User
from .models import Category,Product

# Create your views here.
def index(request):
    items=Product.objects.all()
    return render(request,'index.html',{'items':items})



def register(request):

    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        password1=request.POST['password1']
        if password==password1:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username already exist')
                return redirect('medishop:register')
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save()
                return redirect('medishop:login')
        else:
            messages.info(request,'password already exist')
            return redirect('medishop:register')
        return redirect('/')
    return render(request,'register.html')

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid user')
            return redirect('medishop:login')
    return render(request,'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')


def detail(request, product_id):
    if request.user.is_authenticated:
        item = Product.objects.get(id=product_id)
    else:
        return redirect('medishop:login')
    return render(request, 'detail.html', {'item': item})

def alloitems(request):
    items=Product.objects.filter(category=1)
    return render(request,'index.html',{'items':items})
def homeitems(request):
    items=Product.objects.filter(category=2)
    return render(request,'index.html',{'items':items})
def ayuritems(request):
    items=Product.objects.filter(category=3)
    return render(request,'index.html',{'items':items})

def thank(request):
    return render(request,'thank.html')

medishop/medishopproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link type="text/css" href="{% static 'css/custom.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" >
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'new.css' %}">

</head>
<body>
<div>


    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}

</div>

{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"> </script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>


</body>
</html>

medishop/medishopproject/templates/cart.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="">All Products</a></li>

            <li><a class="dropdown-item" href=""> {{cat.name}}</a></li>
            <a class="dropdown-item"href="https://en.wikipedia.org/wiki/Thiruvananthapuram">tvm</a></li>
     <li> <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">kollam</a></li>
     <li> <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Pathanamthitta">pathanamthitta</a></li>
      <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alapuzha">Alappuzha</a></li>
      <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a></li>
      <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Idukki">Idukki</a></li>
      <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ekm</a></li>
      <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
      <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakad">Palakad</a></li>

          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

medishop/medishopproject/templates/detail.html
{% extends 'base.html' %}

{% block content %}



<div class="card" style="width:20%;margin:55px 500px 40px;text-align:center;">
  <img src="{{item.img.url}}" alt="Denim Jeans" style="width:100%">
  <h1 >{{item.name}}</h1>
 <h4> <p  style="color:red">${{item.price}}</p></h4>
  <p style="padding-left:12px">Some text about the jeans. Super slim and comfy lorem ipsum lorem jeansum. Lorem jeamsun denim lorem jeansum.</p>
    <div style="margin-left:20px;margin-right:20px;margin-bottom:10px">
    <a href="{% url 'medishop:thank' %}"  class="btn btn-primary btn-block my_custom_button" >Buy It</a>
    <a  href="{% url 'medishop:index' %}" class="btn btn-danger btn-block my_custom_button"  >Cancel</a>
</div>

</div>
{% endblock %}

medishop/medishopproject/templates/footer.html
{% load static %}
<div class="footer navbar-fixed-bottom my_footer" style="padding-top:20pxpx;">
  <p class="text-center">&copy; MedIciTY tech pvt ltd.All right Reserved </p>
</div>

medishop/medishopproject/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row mx_auto">
{% for i in items %}
        <div style="margin-bottom:30px;" class=" col-9 col-sm-12 col-md-4  xol-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                 <img class="card-img-top " src="{{i.img.url}}" alt="{{product.name}}" height="250"></a>
                <div class="card-body">

                    <h4>{{i.name}}</h4>
                    <p style="color:red;">₹{{i.price}}</p>
                    <a href="{% url 'medishop:detail' i.id %}" type="button" class="btn btn-success">Purchase</a>

                </div>
            </div>

        </div><br>
        {% endfor %}

    </div>

</div>
{% endblock %}

medishop/medishopproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .contact{
         position: absolute;
    top: 25%;
    left: 35%;

    width: 183px;
    height: 100px;
    padding:30px 80px 240px ;
    background: rgba(0,0,0,0.6);
    }
    input {
  height: 20px;
  flex: 0 0 200px;
  margin-left: 20px;
  margin-bottom: 10px;
  margin-top: 8px;


}
 .btn{

    margin-left:55px;
    color:red;
 }
 h1{
    margin-left:55px;
 }

    </style>
</head>
<body>

<img width=100% src="https://thumbs.dreamstime.com/b/doctor-stethoscope-hand-hospital-background-gown-94227568.jpg">
<form class="contact" action="{% url 'medishop:login' %}" method="post">
        {% csrf_token %}
        <div>
            <h1 ><u><b></b>LOGIN</b></u></h1><br>
            <input type="text" name="username" placeholder="Enter username"><br>
            <input type="password" name="password" placeholder="password"><br>
            <input type="submit" >    <h3><a href="{% url 'medishop:register' %}">Register</a></h3>

        </div>
        {% for msg in messages %}
<h2 style="text-align:center;color:red">{{msg}}</h2>
{% endfor %}
    </form>

</body>
</html>

medishop/medishopproject/templates/navbar.html
<nav class="navbar navbar-expand-lg  bg-dark">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Cities
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
           <li> <a class="dropdown-item"href="https://en.wikipedia.org/wiki/Thiruvananthapuram">tvm</a></li>
           <li> <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">kollam</a></li>
           <li> <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Pathanamthitta">pathanamthitta</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alapuzha">Alappuzha</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Idukki">Idukki</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ekm</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakad">Palakad</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram">Malappuram</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Wayanad">Wayanad</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur">Kannur</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kasaragod">Kasaragod</a></li>


          </ul>

        </li>
           <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            MEDICINES
          </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
           <li> <a class="dropdown-item"href="{% url 'medishop:alloitems' %}">Alopathy</a></li>
           <li> <a class="dropdown-item" href="{% url 'medishop:homeitems' %}">Homeopathy</a></li>
                <li> <a class="dropdown-item" href="{% url 'medishop:ayuritems' %}">Ayurvedic</a></li>

            </ul></li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'medishop:login' %}">LOGIN</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'medishop:register' %}">REGISTER</a>
        </li>
        <li class="nav-item" >
          <a class="nav-link " style="color:gray;" href="{% url 'medishop:logout' %}">logout</a>
        </li>
      </ul>


    </div>
  </div>
</nav>

medishop/medishopproject/templates/register.html
<!DOCTYPE html>
<html>
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for all buttons */
button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Extra styles for the cancel button */
.cancelbtn {
  padding: 14px 20px;
  background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Add padding to container elements */
.container {
  padding: 16px;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
     width: 100%;
  }
}
</style>
<body>

<form action="{% url 'medishop:register' %}" method="post" style="border:1px solid #ccc; width:500px;margin-left:28%">
{% csrf_token %}
  <div class="container">
    <h1>Sign Up</h1>
    <p>Please fill in this form to create an account.</p>
    <hr>

    <label> <b>USER NAME</b></label>
    <input type="text" placeholder="Enter Your Name" name="username" required>

    <label ><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>

    <label ><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="password1" required>

    <label>
      <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
    </label>

    <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>

    <div class="clearfix">
      <button type="submit" class="signupbtn">Sign Up</button>
    </div>
  </div>
</form>

{% for msg in messages %}
<h2 style="text-color:red">{{msg}}</h2>
{% endfor %}


</body>
</html>

medishop/medishopproject/templates/sample.html
{% extends 'base.html' %}
{% block content %}
hai
{% endblock %}

medishop/medishopproject/templates/thank.html
<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>

<div class="w3-container">

  <div class="w3-white w3-hover-shadow w3-padding-64 w3-center" style="width:70%;margin:180px 90px 50px 170px;">
   <h4> <p style="color:green">Thanks for Purchasing...visit again</p></h4>
      <a style="color:gray" href="{% url 'medishop:index' %}"   >Back Home</a>

  </div>
</div>


</body>
</html>